# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: docker build -f "./Dockerfile_tests" -t AutomationImages/spirit-stream/test:latest .
  displayName: 'Build docker image'

- script: docker push AutomationImages/spirit-stream/main:latest
  displayName: 'Push docker image'
